@baseUrl = http://localhost:3333
@eventId = ed92b444-8e83-4a79-bc84-28ae9363b915

# @name get_home
GET {{baseUrl}}
Content-Type: application/json

###

# @name create_event
POST  {{baseUrl}}/events 
Content-Type: application/json


{
    "title": "Create Event Test one attendee",
    "details": "limite de participantes é 1",
    "maximumAttendees": 1
}

###

# @name register_in_event
POST  {{baseUrl}}/events/{{eventId}}/attendees
Content-Type: application/json


{
    "name": "João Ferreira",
    "email": "testemail2@example.com"
}
