@baseUrl = http://localhost:3333
@eventId = ee6c246a-649a-42a2-aa70-015f624ddfcf
@attendeeId = 2

# @name get_home
GET {{baseUrl}}
Content-Type: application/json

###

# @name create_event
POST  {{baseUrl}}/events 
Content-Type: application/json


{
    "title": "Create Event Test one attendee 2",
    "details": "limite de participantes é 1",
    "maximumAttendees": 1
}

###

# @name register_in_event
POST  {{baseUrl}}/events/{{eventId}}/attendees
Content-Type: application/json


{
    "name": "Ivone Carla",
    "email": "testemail3@example.com"
}

###

# @name get_event_data
GET   {{baseUrl}}/events/{{eventId}}
Content-Type: application/json

###

# @name get_attendee_data
GET  {{baseUrl}}/attendees/{{attendeeId}}/badge
Content-Type: application/json

###
# @name get_check_in
GET  {{baseUrl}}/attendees/{{attendeeId}}/check-in
Content-Type: application/json

###

# @name get_many_attendees
GET   {{baseUrl}}/events/{{eventId}}/attendees?query=alex
Content-Type: application/json

